//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID_Clients { get; set; }
        public string ClientsName { get; set; }
        public string ClientsSurname { get; set; }
        public string ClientsAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
