//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicess
    {
        public int ID_Servicess { get; set; }
        public string ServiceName { get; set; }
        public decimal Cost { get; set; }
        public int Duration { get; set; }
    }
}
